package com.virginiaprivacy.sdr.tuner.e4k

/**
 * Auto Gain Control Mode
 * Possible settings:
 * Serial - Manual control via I2C
 * PWM - the tuner adjusts gain based on a digital signal generated by the user
 * Autonomous - the tuner automatically adjusts gain based on received signal levels
 * Supervisor - the tuner will determine gain values automatically, but the use must instruct it before it will change them
 *
 */
sealed class AGCMode(val value: Byte) {
    object SERIAL : AGCMode(0.toByte())
    object IF_PWM_LNA_SERIAL : AGCMode(1.toByte())
    object IF_PWM_LNA_AUTONL : AGCMode(2.toByte())
    object IF_PWM_LNA_SUPERV : AGCMode(3.toByte())
    object IF_SERIAL_LNA_PWM : AGCMode(
        4.toByte()
    )

    object IF_PWM_LNA_PWM : AGCMode(5.toByte())
    object IF_DIG_LNA_SERIAL : AGCMode(6.toByte())
    object IF_DIG_LNA_AUTON : AGCMode(7.toByte())
    object IF_DIG_LNA_SUPERV : AGCMode(8.toByte())
    object IF_SERIAL_LNA_AUTON : AGCMode(
        9.toByte()
    )

    object IF_SERIAL_LNA_SUPERV : AGCMode(10.toByte())
    companion object {
        fun values(): Array<AGCMode> {
            return arrayOf(
                SERIAL,
                IF_PWM_LNA_SERIAL,
                IF_PWM_LNA_AUTONL,
                IF_PWM_LNA_SUPERV,
                IF_SERIAL_LNA_PWM,
                IF_PWM_LNA_PWM,
                IF_DIG_LNA_SERIAL,
                IF_DIG_LNA_AUTON,
                IF_DIG_LNA_SUPERV,
                IF_SERIAL_LNA_AUTON,
                IF_SERIAL_LNA_SUPERV
            )
        }

        fun valueOf(value: String): AGCMode {
            return when (value) {
                "SERIAL" -> SERIAL
                "IF_PWM_LNA_SERIAL" -> IF_PWM_LNA_SERIAL
                "IF_PWM_LNA_AUTONL" -> IF_PWM_LNA_AUTONL
                "IF_PWM_LNA_SUPERV" -> IF_PWM_LNA_SUPERV
                "IF_SERIAL_LNA_PWM" -> IF_SERIAL_LNA_PWM
                "IF_PWM_LNA_PWM" -> IF_PWM_LNA_PWM
                "IF_DIG_LNA_SERIAL" -> IF_DIG_LNA_SERIAL
                "IF_DIG_LNA_AUTON" -> IF_DIG_LNA_AUTON
                "IF_DIG_LNA_SUPERV" -> IF_DIG_LNA_SUPERV
                "IF_SERIAL_LNA_AUTON" -> IF_SERIAL_LNA_AUTON
                "IF_SERIAL_LNA_SUPERV" -> IF_SERIAL_LNA_SUPERV
                else -> throw IllegalArgumentException("No object com.virginiaprivacy.sdr.tuner.e4k.AGCMode.$value")
            }
        }
    }
}

class AutonomousGainControl